int _putchar(char c);
void print_alphabet(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_jack_baver(void);
void times_tablet(void);
int add(int,int);
void print_to_98(int n);
void print_times_tablet(int n);
